<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.537">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Biostat 200C Homework 5</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="hw5sol_files/libs/clipboard/clipboard.min.js"></script>
<script src="hw5sol_files/libs/quarto-html/quarto.js"></script>
<script src="hw5sol_files/libs/quarto-html/popper.min.js"></script>
<script src="hw5sol_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="hw5sol_files/libs/quarto-html/anchor.min.js"></script>
<link href="hw5sol_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="hw5sol_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="hw5sol_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="hw5sol_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="hw5sol_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Biostat 200C Homework 5</h1>
<p class="subtitle lead">Due June 3 @ 11:59PM</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(faraway)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: Matrix</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'Matrix'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:tidyr':

    expand, pack, unpack</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reshape2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'reshape2'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:tidyr':

    smiths</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'MASS'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    select</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(geepack)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'geepack'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:faraway':

    ohio</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(faraway)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="q1.-balanced-one-way-anova-random-effects-model" class="level2">
<h2 class="anchored" data-anchor-id="q1.-balanced-one-way-anova-random-effects-model">Q1. Balanced one-way ANOVA random effects model</h2>
<p>Consider the balanced one-way ANOVA random effects model with <span class="math inline">\(a\)</span> levels and <span class="math inline">\(n\)</span> observations in each level <span class="math display">\[
y_{ij} = \mu + \alpha_i + \epsilon_{ij}, \quad i=1,\ldots,a, \quad j=1,\ldots,n.
\]</span> where <span class="math inline">\(\alpha_i\)</span> are iid from <span class="math inline">\(N(0,\sigma_\alpha^2)\)</span>, <span class="math inline">\(\epsilon_{ij}\)</span> are iid from <span class="math inline">\(N(0, \sigma_\epsilon^2)\)</span>.</p>
<ol type="1">
<li>Derive the ANOVA estimate for <span class="math inline">\(\mu\)</span>, <span class="math inline">\(\sigma_\alpha^2\)</span>, and <span class="math inline">\(\sigma_{\epsilon}^2\)</span>. Specifically show that <span class="math display">\[\begin{eqnarray*}
  \mathbb{E}(\bar y_{\cdot \cdot}) &amp;=&amp; \mathbb{E} \left( \frac{\sum_{ij} y_{ij}}{na} \right) = \mu \\
  \mathbb{E} (\text{SSE}) &amp;=&amp; \mathbb{E} \left[ \sum_{i=1}^a \sum_{j=1}^n (y_{ij} - \bar{y}_{i \cdot})^2 \right] = a(n-1) \sigma_{\epsilon}^2 \\
  \mathbb{E} (\text{SSA}) &amp;=&amp; \mathbb{E} \left[ \sum_{i=1}^a \sum_{j=1}^n (\bar{y}_{i \cdot} - \bar{y}_{\cdot \cdot})^2 \right] = (a-1)(n \sigma_{\alpha}^2 + \sigma_{\epsilon}^2),
\end{eqnarray*}\]</span> which can be solved to obtain ANOVA estimate <span class="math display">\[\begin{eqnarray*}
\widehat{\mu} &amp;=&amp; \frac{\sum_{ij} y_{ij}}{na}, \\
\widehat{\sigma}_{\epsilon}^2 &amp;=&amp; \frac{\text{SSE}}{a(n-1)}, \\
\widehat{\sigma}_{\alpha}^2 &amp;=&amp; \frac{\text{SSA}/(a-1) - \widehat{\sigma}_{\epsilon}^2}{n}.
\end{eqnarray*}\]</span></li>
</ol>
<p><strong>Answer:</strong></p>
<p><span class="math inline">\(E(\bar{y}..) = E(\frac{\sum_{ij} y_{ij}}{na}) = \frac{\sum_{ij} E(y_{ij})}{na} = \frac{\sum_{ij} \mu}{na}=\frac{na\mu}{na}=\mu\)</span></p>
<p><span class="math inline">\(\vec{Y} = \mu \vec{\mathbb{1}}_{na} + Z\vec{\alpha} +\vec{\epsilon}\)</span> where <span class="math inline">\(Z=I_a \otimes \mathbb{1}_{n\times n}\)</span> and <span class="math inline">\(\epsilon \sim N(0, \sigma_\epsilon^2 I_{na})\)</span></p>
<p><span class="math inline">\(Cov(\vec{Y})=ZZ'\sigma_a^2+\sigma_{\epsilon}^2I_{na}\)</span></p>
<p>define</p>
<p><span class="math display">\[\begin{align}
  y &amp;= \begin{bmatrix}
         y_{i1} \\
         y_{i2} \\
         \vdots \\
         y_{in}
       \end{bmatrix}
\end{align}\]</span></p>
<p><span class="math inline">\(\bar{y}_{i.} = \frac{1}{n} \sum_{j=1}^{n} y_{ij}=\frac{1}{n}\mathbb{1_n'}y_i\)</span></p>
<p><span class="math inline">\(y_i-\bar{y}_{i.} = y_i - \frac{1}{n}\mathbb{1_n'}y_i = (I_n-\frac{1}{n}\mathbb{1_n}\mathbb{1_n'})y_i\)</span></p>
<p>Then we can rewrite it as:</p>
<p><span class="math inline">\(SSE=\vec{y}'A_1\vec{y}\)</span></p>
<p><span class="math display">\[\begin{align}
  A_1 &amp;= \begin{bmatrix}
            I_n-n^{-1}\mathbb{1_n}\mathbb{1_n'} &amp; &amp; \\
            &amp; \ddots &amp; \\
            &amp; &amp; I_n-n^{-1}\mathbb{1_n}\mathbb{1_n'}
         \end{bmatrix}
\end{align}\]</span></p>
<p><span class="math display">\[\begin{align}
E(SSE)&amp;=E(\vec{y}'A_1\vec{y})\\
&amp;=E(trA_1\vec{y}\vec{y}')\\
&amp;=trA_1Cov(\vec{y})\\
&amp;=trA_1(ZZ'\sigma_a^2+\sigma_{\epsilon}^2I_{na})+\mu^2trA_1\mathbb{1_na}\mathbb{1'_na}\\
&amp;=0+a(n-1)\sigma^2_\epsilon+0\\
&amp;=a(n-1)\sigma^2_\epsilon
\end{align}\]</span></p>
<p><span class="math inline">\(SSA=\vec{y}'A_0\vec{y}\)</span></p>
<p>where <span class="math inline">\(A_0=I_{na}-\frac{1}{an}\mathbb{1_{na}}\mathbb{1_{na}'}\)</span></p>
<p><span class="math display">\[\begin{align}
E(SST)&amp;=trA_0(\sigma_a^2ZZ'+\sigma_{\epsilon}^2I_{na})+\mu^2trA_0\mathbb{1_na}\mathbb{1'_na}\\
&amp;=n(a-1)\sigma_a^2+\sigma_{\epsilon}^2(na-1)+0\\
&amp;=n(a-1)\sigma_a^2+\sigma_{\epsilon}^2(na-1)
\end{align}\]</span></p>
<p><span class="math display">\[
\mathbb{E}(\text{SSA}) = \mathbb{E}(\text{SST}) - \mathbb{E}(\text{SSE}) = (a - 1)(n \sigma_{\alpha}^2 + \sigma_{\epsilon}^2).
\]</span></p>
<ol start="2" type="1">
<li>Derive the MLE estimate for <span class="math inline">\(\mu\)</span>, <span class="math inline">\(\sigma_\alpha^2\)</span>, and <span class="math inline">\(\sigma_{\epsilon}^2\)</span>. Hint: write down the log-likelihood and find the maximizer.</li>
</ol>
<p>The log-likelihodd is <span class="math display">\[\begin{eqnarray*}
    \ell(\mu, \sigma_{\alpha}^2, \sigma_{\epsilon}^2) &amp;=&amp; - \frac n2 \log(2\pi) - \frac 12 \log \det (\sigma_{\alpha}^2 \mathbf{Z} \mathbf{Z}^T + \sigma_{\epsilon}^2 \mathbf{I}) - \frac 12 (\mathbf{y} - \mathbf{1}_{na} \mu)^T (\sigma_{\alpha}^2 \mathbf{Z} \mathbf{Z}^T + \sigma_{\epsilon}^2 \mathbf{I})^{-1} (\mathbf{y} - \mathbf{1}_{na} \mu) \\
    &amp;=&amp; \sum_i - \frac 12 \log \det (\sigma_{\alpha}^2 \mathbf{1}_n \mathbf{1}_n^T + \sigma_{\epsilon}^2 \mathbf{I}_n) - \frac 12 (\mathbf{y}_i - \mathbf{1}_{n} \mu)^T (\sigma_{\alpha}^2 \mathbf{1}_n \mathbf{1}_n^T + \sigma_{\epsilon}^2 \mathbf{I}_n)^{-1} (\mathbf{y}_i - \mathbf{1}_{n} \mu).
    \end{eqnarray*}\]</span> By Woodbury formula <span class="math display">\[\begin{eqnarray*}
    (\sigma_{\alpha}^2 \mathbf{1}_n \mathbf{1}_n^T + \sigma_{\epsilon}^2 \mathbf{I}_n)^{-1} &amp;=&amp; \sigma_{\epsilon}^{-2} \mathbf{I}_{n} - \frac{\sigma_{\epsilon}^{-2} \sigma_{\alpha}^2}{\sigma_{\epsilon}^2 + n\sigma_{\alpha}^2} \mathbf{1}_n \mathbf{1}_n^T \\
    \det (\sigma_{\alpha}^2 \mathbf{1}_n \mathbf{1}_n^T + \sigma_{\epsilon}^2 \mathbf{I}_n) &amp;=&amp; \sigma_{\epsilon}^{2n} (1 + n \sigma_{\alpha}^2 / \sigma_{\epsilon}^2).
    \end{eqnarray*}\]</span> Let <span class="math inline">\(\lambda = \sigma_\alpha^2 / \sigma_\epsilon^2\)</span>, then the log-likelihood is <span class="math display">\[\begin{eqnarray*}
    \ell(\mu, \sigma_{\alpha}^2, \sigma_{\epsilon}^2) &amp;=&amp; - \frac{na}{2} \log \sigma_{\epsilon}^2 - \frac{a}{2} \log (1 + n\lambda) - \frac{\sigma_{\epsilon}^{-2}}{2} \text{SST}(\mu) + \frac{\sigma_{\epsilon}^{-2}}{2} \frac{n\lambda}{1 + n \lambda} \text{SSA}(\mu) \\
    &amp;=&amp; - \frac{na}{2} \log \sigma_{\epsilon}^2 - \frac{a}{2} \log (1 + n\lambda) - \frac{\sigma_{\epsilon}^{-2}}{2} \frac{\text{SST}(\mu) + n\lambda \text{SSA}}{1 + n \lambda}.
    \end{eqnarray*}\]</span> Setting derivative with respect to <span class="math inline">\(\mu\)</span> to 0 yields <span class="math display">\[
    \hat \mu = \bar y_{\cdot \cdot}.
    \]</span> Setting derivative with respect to <span class="math inline">\(\sigma_{\epsilon}^2\)</span> to 0 yields equation <span class="math display">\[
    \sigma_{\epsilon}^2 = \frac{\text{SST} - \frac{n\lambda}{1 + n\lambda} \text{SSA}}{na} = \frac{\text{SST} + n \lambda \text{SSE}}{na(1 + n\lambda)}.
    \]</span> Substitution of the above expression into the log-likelihood shows we need to maximize <span class="math display">\[\begin{eqnarray*}
    &amp; &amp; - \frac{na}{2} \log \left( \text{SST} - \frac{n\lambda}{1 + n\lambda} \text{SSA} \right) - \frac{a}{2} \log (1 + n\lambda) \\
    &amp;=&amp; - \frac{na}{2} \log \left( \text{SST} + n \lambda \text{SSE} \right) + \frac{(n-1)a}{2} \log (1 + n \lambda).
    \end{eqnarray*}\]</span> Setting derivative to 0 gives the maximizer <span class="math display">\[
    \hat \lambda = \frac{n-1}{n} \frac{\text{SST}}{\text{SSE}} - 1.
    \]</span> Thus <span class="math display">\[
    \hat \sigma_{\epsilon}^2 = \frac{\text{SST} - \frac{n \hat \lambda}{1 + n \hat \lambda} \text{SSA}}{na} = \frac{\text{SSE}}{(n-1)a}
    \]</span> (same as ANOVA estimate) and <span class="math display">\[
    \hat \sigma_{\alpha}^2 = \frac{\text{SSA}}{an} - \frac{\text{SSE}}{an(n-1)}.
    \]</span></p>
<p><span class="math display">\[ L(\mu, \sigma_\alpha^2, \sigma_\epsilon^2) = \prod_{i=1}^{a} \prod_{j=1}^{n} \frac{1}{\sqrt{2 \pi (\sigma_\alpha^2 + \sigma_\epsilon^2)}} \exp \left( -\frac{(y_{ij} - \mu)^2}{2(\sigma_\alpha^2 + \sigma_\epsilon^2)} \right) \]</span></p>
<p><span class="math display">\[ \ell(\mu, \sigma_\alpha^2, \sigma_\epsilon^2) = -\frac{an}{2} \log(2\pi) - \frac{an}{2} \log(\sigma_\alpha^2 + \sigma_\epsilon^2) - \frac{1}{2(\sigma_\alpha^2 + \sigma_\epsilon^2)} \sum_{i=1}^{a} \sum_{j=1}^{n} (y_{ij} - \mu)^2 \]</span></p>
<p><span class="math display">\[ \frac{\partial \ell}{\partial \mu} = \frac{1}{\sigma_\alpha^2 + \sigma_\epsilon^2} \sum_{i=1}^{a} \sum_{j=1}^{n} (y_{ij} - \mu) \]</span></p>
<p>Setting this to zero:</p>
<p><span class="math display">\[ \sum_{i=1}^{a} \sum_{j=1}^{n} (y_{ij} - \mu) = 0 \]</span></p>
<p><span class="math display">\[ \sum_{i=1}^{a} \sum_{j=1}^{n} y_{ij} = \sum_{i=1}^{a} \sum_{j=1}^{n} \mu \]</span></p>
<p><span class="math display">\[ \mu = \frac{1}{an} \sum_{i=1}^{a} \sum_{j=1}^{n} y_{ij} \]</span></p>
<p>So the MLE for <span class="math inline">\(\mu\)</span> is:</p>
<p><span class="math display">\[ \hat{\mu} = \frac{1}{an} \sum_{i=1}^{a} \sum_{j=1}^{n} y_{ij} \]</span></p>
<p>Similarly, we can derive the MLE for <span class="math inline">\(\sigma_\alpha^2\)</span> and <span class="math inline">\(\sigma_\epsilon^2\)</span> with the same procedures:</p>
<p><span class="math display">\[ \hat{\sigma}_\epsilon^2 = \frac{\text{SSE}}{a(n-1)} \]</span></p>
<p><span class="math display">\[ \hat{\sigma}_\alpha^2 = \frac{\text{SSA} / (a-1) - \hat{\sigma}_\epsilon^2}{n} \]</span></p>
<p>Where:</p>
<p><span class="math display">\[ \text{SSE} = \sum_{i=1}^{a} \sum_{j=1}^{n} (y_{ij} - \bar{y}_{i.})^2 \]</span></p>
<p><span class="math display">\[ \text{SSA} = \sum_{i=1}^{a} n (\bar{y}_{i.} - \bar{y}_{..})^2 \]</span></p>
<ol start="3" type="1">
<li><p>(<strong>Optional</strong>) Derive the REML estimate for <span class="math inline">\(\mu\)</span>, <span class="math inline">\(\sigma_\alpha^2\)</span>, and <span class="math inline">\(\sigma_{\epsilon}^2\)</span>.</p></li>
<li><p>For all three estimates, check that your results match those we obtained using R for the <code>pulp</code> example in class.</p></li>
</ol>
<p><strong>Answer:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(pulp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(pulp<span class="sc">$</span>bright)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 60.4</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>(aovmod <span class="ot">&lt;-</span> <span class="fu">aov</span>(bright <span class="sc">~</span> operator, <span class="at">data =</span> pulp) <span class="sc">%&gt;%</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Df Sum Sq Mean Sq F value Pr(&gt;F)  
operator     3   1.34  0.4467   4.204 0.0226 *
Residuals   16   1.70  0.1062                 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>(aovmod[<span class="dv">1</span>][[<span class="dv">1</span>]][[<span class="dv">3</span>]][<span class="dv">1</span>] <span class="sc">-</span> aovmod[<span class="dv">1</span>][[<span class="dv">1</span>]][[<span class="dv">3</span>]][<span class="dv">2</span>]) <span class="sc">/</span> <span class="dv">5</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.06808333</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>aovmod[<span class="dv">1</span>][[<span class="dv">1</span>]][[<span class="dv">3</span>]][<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.10625</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>overall_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(pulp<span class="sc">$</span>bright)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>factor_means <span class="ot">&lt;-</span> pulp <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(operator) <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean_bright =</span> <span class="fu">mean</span>(bright))</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>SSE <span class="ot">&lt;-</span> pulp <span class="sc">%&gt;%</span></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(operator) <span class="sc">%&gt;%</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">sum_sq =</span> <span class="fu">sum</span>((bright <span class="sc">-</span> <span class="fu">mean</span>(bright))<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">SSE =</span> <span class="fu">sum</span>(sum_sq)) <span class="sc">%&gt;%</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(SSE)</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>SSA <span class="ot">&lt;-</span> factor_means <span class="sc">%&gt;%</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">SSA =</span> <span class="fu">sum</span>(<span class="fu">n</span>() <span class="sc">*</span> (mean_bright <span class="sc">-</span> overall_mean)<span class="sc">^</span><span class="dv">2</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb28-14"><a href="#cb28-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(SSA)</span>
<span id="cb28-15"><a href="#cb28-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-16"><a href="#cb28-16" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">nlevels</span>(pulp<span class="sc">$</span>operator)</span>
<span id="cb28-17"><a href="#cb28-17" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(pulp) <span class="sc">/</span> a</span>
<span id="cb28-18"><a href="#cb28-18" aria-hidden="true" tabindex="-1"></a>sigma2_epsilon <span class="ot">&lt;-</span> SSE <span class="sc">/</span> (a <span class="sc">*</span> (n <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb28-19"><a href="#cb28-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-20"><a href="#cb28-20" aria-hidden="true" tabindex="-1"></a>sigma2_alpha <span class="ot">&lt;-</span> (SSA <span class="sc">/</span> (a <span class="sc">-</span> <span class="dv">1</span>) <span class="sc">-</span> sigma2_epsilon) <span class="sc">/</span> n</span>
<span id="cb28-21"><a href="#cb28-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-22"><a href="#cb28-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Print results</span></span>
<span id="cb28-23"><a href="#cb28-23" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"SSE:"</span>, SSE, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>SSE: 1.7 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"SSA:"</span>, SSA, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>SSA: 1.072 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"sigma^2_epsilon:"</span>, sigma2_epsilon, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>sigma^2_epsilon: 0.10625 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"sigma^2_alpha:"</span>, sigma2_alpha, <span class="st">"</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>sigma^2_alpha: 0.05021667 </code></pre>
</div>
</div>
<p><span class="math inline">\(\sigma^2_{\epsilon}\)</span> does not match.</p>
</section>
<section id="q2.-estimation-of-random-effects" class="level2">
<h2 class="anchored" data-anchor-id="q2.-estimation-of-random-effects">Q2. Estimation of random effects</h2>
<ol type="1">
<li>Assume the conditional distribution <span class="math display">\[
\mathbf{y} \mid \boldsymbol{\gamma} \sim N(\mathbf{X} \boldsymbol{\beta} + \mathbf{Z} \boldsymbol{\gamma}, \sigma^2 \mathbf{I}_n)
\]</span> and the prior distribution <span class="math display">\[
\boldsymbol{\gamma} \sim N(\mathbf{0}_q, \boldsymbol{\Sigma}).
\]</span> Then by the Bayes theorem, the posterior distribution is <span class="math display">\[\begin{eqnarray*}
f(\boldsymbol{\gamma} \mid \mathbf{y}) &amp;=&amp; \frac{f(\mathbf{y} \mid \boldsymbol{\gamma}) \times f(\boldsymbol{\gamma})}{f(\mathbf{y})}, \end{eqnarray*}\]</span> where <span class="math inline">\(f\)</span> denotes corresponding density. Show that the posterior distribution is a multivariate normal with mean <span class="math display">\[
\mathbb{E} (\boldsymbol{\gamma} \mid \mathbf{y}) = \boldsymbol{\Sigma} \mathbf{Z}^T (\mathbf{Z} \boldsymbol{\Sigma} \mathbf{Z}^T + \sigma^2 \mathbf{I})^{-1} (\mathbf{y} - \mathbf{X} \boldsymbol{\beta}).
\]</span></li>
</ol>
<p><strong>Answer:</strong></p>
<p>Assume the conditional distribution</p>
<p><span class="math display">\[ y \mid \gamma \sim N(X\beta + Z\gamma, \sigma^2 I_n) \]</span></p>
<p>and the prior distribution</p>
<p><span class="math display">\[ \gamma \sim N(0, \Sigma). \]</span></p>
<p>Then by Bayes’ theorem, the posterior distribution is</p>
<p><span class="math display">\[ f(\gamma \mid y) = \frac{f(y \mid \gamma) \times f(\gamma)}{f(y)}, \]</span></p>
<p>where f denotes the corresponding density.</p>
<p>The likelihood function is</p>
<p><span class="math display">\[ f(y \mid \gamma) = \frac{1}{(2\pi \sigma^2)^{n/2}} \exp\left( -\frac{1}{2\sigma^2} (y - X\beta - Z\gamma)^\top (y - X\beta - Z\gamma) \right). \]</span></p>
<p>The prior density is</p>
<p><span class="math display">\[ f(\gamma) = \frac{1}{(2\pi)^{q/2} \lvert \Sigma \rvert^{1/2}} \exp\left( -\frac{1}{2} \gamma^\top \Sigma^{-1} \gamma \right). \]</span></p>
<p>Therefore, the posterior distribution is proportional to the product of these densities:</p>
<p><span class="math display">\[ f(\gamma \mid y) \propto \exp\left( -\frac{1}{2\sigma^2} (y - X\beta - Z\gamma)^\top (y - X\beta - Z\gamma) \right) \times \exp\left( -\frac{1}{2} \gamma^\top \Sigma^{-1} \gamma \right). \]</span></p>
<p>Combining the exponents, we get</p>
<p><span class="math display">\[ f(\gamma \mid y) \propto \exp\left( -\frac{1}{2} \left[ \frac{1}{\sigma^2} (y - X\beta - Z\gamma)^\top (y - X\beta - Z\gamma) + \gamma^\top \Sigma^{-1} \gamma \right] \right). \]</span></p>
<p>Expanding the term inside the exponent:</p>
<p><span class="math display">\[ \frac{1}{\sigma^2} (y - X\beta - Z\gamma)^\top (y - X\beta - Z\gamma) = \frac{1}{\sigma^2} \left[ (y - X\beta)^\top (y - X\beta) - 2 (y - X\beta)^\top Z\gamma + \gamma^\top Z^\top Z\gamma \right], \]</span></p>
<p>so the posterior can be rewritten as:</p>
<p><span class="math display">\[ f(\gamma \mid y) \propto \exp\left( -\frac{1}{2} \left[ \frac{1}{\sigma^2} (y - X\beta)^\top (y - X\beta) - \frac{2}{\sigma^2} (y - X\beta)^\top Z\gamma + \left( \frac{1}{\sigma^2} Z^\top Z + \Sigma^{-1} \right) \gamma^\top \gamma \right] \right). \]</span></p>
<p>To simplify, complete the square for <span class="math inline">\(\gamma\)</span>:</p>
<p><span class="math display">\[ \left( \frac{1}{\sigma^2} Z^\top Z + \Sigma^{-1} \right) \gamma^\top \gamma - \frac{2}{\sigma^2} (y - X\beta)^\top Z \gamma = \left( \gamma - \hat{\gamma} \right)^\top \left( \frac{1}{\sigma^2} Z^\top Z + \Sigma^{-1} \right) \left( \gamma - \hat{\gamma} \right) + \text{constant}, \]</span></p>
<p>where</p>
<p><span class="math display">\[ \hat{\gamma} = \left( \frac{1}{\sigma^2} Z^\top Z + \Sigma^{-1} \right)^{-1} \frac{1}{\sigma^2} Z^\top (y - X\beta). \]</span></p>
<p>Thus, the posterior distribution is</p>
<p><span class="math display">\[ \gamma \mid y \sim N\left( \hat{\gamma}, \left( \frac{1}{\sigma^2} Z^\top Z + \Sigma^{-1} \right)^{-1} \right). \]</span></p>
<p>The mean of the posterior distribution is</p>
<p><span class="math display">\[ E(\gamma \mid y) = \hat{\gamma} = \Sigma Z^\top \left( Z \Sigma Z^\top + \sigma^2 I \right)^{-1} (y - X\beta). \]</span></p>
<ol start="2" type="1">
<li>For the balanced one-way ANOVA random effects model, show that the posterior mean of random effects is always a constant (less than 1) multiplying the corresponding fixed effects estimate.</li>
</ol>
<p><strong>Answer:</strong></p>
<p>From the previous derivation, we know the posterior distribution of <span class="math inline">\(\alpha_i\)</span> given the data (y) is:</p>
<p><span class="math display">\[ \alpha_i \mid y \sim N \left( \hat{\alpha}_i, \left( \frac{1}{\sigma^2} Z^\top Z + \Sigma^{-1} \right)^{-1} \right), \]</span></p>
<p>where <span class="math inline">\(\hat{\alpha}_i\)</span> is the posterior mean.</p>
<p>For the balanced one-way ANOVA random effects model, the posterior mean of <span class="math inline">\(\alpha_i\)</span> is:</p>
<p><span class="math display">\[ E(\alpha_i \mid y) = \frac{\sigma_\alpha^2}{\sigma_\alpha^2 + \frac{\sigma_\epsilon^2}{n}} \left( \bar{y}_{i.} - \bar{y}_{..} \right), \]</span></p>
<p>where <span class="math inline">\(\bar{y}_{i.}\)</span> is the mean of the observations in the (i)-th group, and <span class="math inline">\(\bar{y}_{..}\)</span> is the overall mean of all observations.</p>
<p>The fixed effects estimate for <span class="math inline">\(\alpha_i\)</span> is simply <span class="math inline">\(\bar{y}_{i.} - \bar{y}_{..}\)</span>. Thus, the posterior mean of the random effects is:</p>
<p><span class="math display">\[ E(\alpha_i \mid y) = \frac{\sigma_\alpha^2}{\sigma_\alpha^2 + \frac{\sigma_\epsilon^2}{n}} (\bar{y}_{i.} - \bar{y}_{..}). \]</span></p>
<p>Let <span class="math inline">\(\lambda = \frac{\sigma_\alpha^2}{\sigma_\alpha^2 + \frac{\sigma_\epsilon^2}{n}}\)</span></p>
<p>Clearly, <span class="math inline">\(\lambda\)</span> is a constant that is less than 1 because <span class="math inline">\(\sigma_\alpha^2 &gt; 0\)</span> and <span class="math inline">\(\sigma_\epsilon^2 &gt; 0\)</span></p>
<p>Therefore,</p>
<p><span class="math display">\[ E(\alpha_i \mid y) = \lambda (\bar{y}_{i.} - \bar{y}_{..}), \]</span></p>
<p>where <span class="math inline">\(\lambda\)</span> is the shrinkage factor which is always less than 1.</p>
</section>
<section id="q3.-elmr-exercise-11.1-p251" class="level2">
<h2 class="anchored" data-anchor-id="q3.-elmr-exercise-11.1-p251">Q3. ELMR Exercise 11.1 (p251)</h2>
<p><img src="images/WeChat0f150307da69a4fcfa94f08884ec157d.png" class="img-fluid"></p>
<p><strong>(a) Answer:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(ratdrink)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(ratdrink)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>ratdrink <span class="sc">|&gt;</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> weeks, <span class="at">y =</span> wt, <span class="at">group =</span> subject, <span class="at">color =</span> treat))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw5sol_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>ratdrink <span class="sc">|&gt;</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span> </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> weeks, <span class="at">y =</span> wt, <span class="at">group =</span> subject)) <span class="sc">+</span> </span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> treat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw5sol_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can see the weight increases with time for all three groups. The treatment group with added thiouracil seems to increase slower tha the control group and the other treatment group.</p>
<p><strong>(b) Answer:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>mmod <span class="ot">&lt;-</span> <span class="fu">lmer</span>(wt <span class="sc">~</span> weeks <span class="sc">*</span> treat <span class="sc">+</span> (weeks <span class="sc">|</span> subject), <span class="at">data =</span> ratdrink)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML ['lmerMod']
Formula: wt ~ weeks * treat + (weeks | subject)
   Data: ratdrink

REML criterion at convergence: 878.7

Scaled residuals: 
     Min       1Q   Median       3Q      Max 
-1.83136 -0.54991  0.04003  0.58230  2.03660 

Random effects:
 Groups   Name        Variance Std.Dev. Corr 
 subject  (Intercept) 32.49    5.700         
          weeks       14.14    3.760    -0.13
 Residual             18.90    4.348         
Number of obs: 135, groups:  subject, 27

Fixed effects:
                      Estimate Std. Error t value
(Intercept)            52.8800     2.0937  25.256
weeks                  26.4800     1.2661  20.915
treatthiouracil         4.7800     2.9610   1.614
treatthyroxine         -0.7943     3.2628  -0.243
weeks:treatthiouracil  -9.3700     1.7905  -5.233
weeks:treatthyroxine    0.6629     1.9730   0.336

Correlation of Fixed Effects:
            (Intr) weeks  trtthr trtthy wks:trtthr
weeks       -0.250                                
treatthircl -0.707  0.177                         
treatthyrxn -0.642  0.160  0.454                  
wks:trtthrc  0.177 -0.707 -0.250 -0.113           
wks:trtthyr  0.160 -0.642 -0.113 -0.250  0.454    </code></pre>
</div>
</div>
<ul>
<li><p>For control group at weeks 0, the expected weight is 52.88 for a typical individual.</p></li>
<li><p>For every one week increase, the rate of change for expected weight decreases -9.3700 compared to control group for typical individuals.</p></li>
<li><p>The SD of intercept of random effect is 5.7 which might suggests there is slightly large differences between different subjects.</p></li>
</ul>
<p><strong>(c) Answer:</strong></p>
<p>Since the 95% confidence interval of all treatments contains 0, we do not have enough evidence to conclude there is significant difference of effect between treatments and control group.</p>
<p><strong>(d) Answer:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">resid</span>(mmod) <span class="sc">~</span> <span class="fu">fitted</span>(mmod), <span class="at">xlab =</span> <span class="st">"Fitted"</span>, <span class="at">ylab =</span> <span class="st">"Residuals"</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="dv">0</span> )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw5sol_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">resid</span>(mmod), <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw5sol_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The residuals are equally scattered about the x-axis with no evidence of homoscedasticity. Assumptions of linearity and equal variance appear reasoanbly satisfied. QQ plot shows the residuals roughly follow a normal distribution.</p>
<p><strong>(e) Answer:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(mmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Computing profile confidence intervals ...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                            2.5 %     97.5 %
.sig01                  3.4506344  7.6654748
.sig02                 -0.5261017  0.3794396
.sig03                  2.6064086  4.8687660
.sigma                  3.7555591  5.1142342
(Intercept)            48.8692859 56.8907140
weeks                  24.0547425 28.9052574
treatthiouracil        -0.8920062 10.4520061
treatthyroxine         -7.0445322  5.4559606
weeks:treatthiouracil -12.7998320 -5.9401680
weeks:treatthyroxine   -3.1166337  4.4423479</code></pre>
</div>
</div>
</section>
<section id="q4.-elmr-exercise-13.1-p295" class="level2">
<h2 class="anchored" data-anchor-id="q4.-elmr-exercise-13.1-p295">Q4. ELMR Exercise 13.1 (p295)</h2>
<p><img src="images/WeChat2a27766b2b4c4c30b8fffd8a6fd4593b.png" class="img-fluid"></p>
<p><img src="images/WeChat4688fa8a540fa890e33126640bb687c1.png" class="img-fluid"></p>
<p><strong>(a) Answer:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(ohio)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">help</span>(ohio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Help on topic 'ohio' was found in the following packages:

  Package               Library
  faraway               /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
  geepack               /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library


Using the first match ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>ohio <span class="sc">|&gt;</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> smoke, <span class="at">group =</span> id))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw5sol_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>No, no mother changed their smoke status during the study.</p>
<p><strong>(b) Answer:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>wheeze_count <span class="ot">&lt;-</span> ohio <span class="sc">%&gt;%</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(id, smoke) <span class="sc">%&gt;%</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">t =</span> <span class="fu">sum</span>(resp), <span class="at">.groups =</span> <span class="st">'drop'</span>)</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>wheeze_table <span class="ot">&lt;-</span> <span class="fu">table</span>(wheeze_count<span class="sc">$</span>smoke, wheeze_count<span class="sc">$</span>t)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>wheeze_table <span class="ot">&lt;-</span> <span class="fu">as.data.frame.matrix</span>(wheeze_table)</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>wheeze_table<span class="sc">$</span>total <span class="ot">&lt;-</span> <span class="fu">rowSums</span>(wheeze_table)</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>wheeze_table <span class="ot">&lt;-</span> wheeze_table <span class="sc">%&gt;%</span></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> .<span class="sc">/</span>total)) <span class="sc">%&gt;%</span></span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>total)</span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-15"><a href="#cb49-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-16"><a href="#cb49-16" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(wheeze_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          0         1          2          3          4
0 0.6771429 0.1857143 0.07142857 0.03428571 0.03142857
1 0.6310160 0.1711230 0.10160428 0.05882353 0.03743316</code></pre>
</div>
</div>
<p><strong>(c) Answer:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>proportion_table <span class="ot">&lt;-</span> ohio <span class="sc">|&gt;</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(age, smoke) <span class="sc">|&gt;</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">proportion_resp0 =</span> <span class="fu">mean</span>(resp <span class="sc">==</span> <span class="dv">0</span>)) <span class="sc">|&gt;</span></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`summarise()` has grouped output by 'age'. You can override using the `.groups`
argument.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>proportion_table_wide <span class="ot">&lt;-</span> <span class="fu">dcast</span>(proportion_table, age <span class="sc">~</span> smoke, <span class="at">value.var =</span> <span class="st">"proportion_resp0"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>proportion_table<span class="sc">$</span>smoke <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(proportion_table<span class="sc">$</span>smoke)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(proportion_table, <span class="fu">aes</span>(<span class="at">x =</span> age, <span class="at">y =</span> proportion_resp0, <span class="at">color =</span> smoke, <span class="at">group =</span> smoke)) <span class="sc">+</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Proportion of resp == 0 by Age and Smoke Status"</span>,</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Age"</span>,</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Proportion of resp == 0"</span>,</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Smoke Status"</span>) <span class="sc">+</span></span>
<span id="cb55-8"><a href="#cb55-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw5sol_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>(d) Answer:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co">#remove age</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>binomial_df <span class="ot">&lt;-</span> ohio <span class="sc">|&gt;</span></span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(id) <span class="sc">|&gt;</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">total_resp =</span> <span class="fu">sum</span>(resp), </span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">smoke =</span> <span class="fu">first</span>(smoke)) <span class="sc">|&gt;</span></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">smoke =</span> <span class="fu">as.factor</span>(smoke))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>glmmod <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="fu">cbind</span>(total_resp, <span class="dv">4</span> <span class="sc">-</span> total_resp) <span class="sc">~</span> smoke, <span class="at">data =</span> binomial_df, <span class="at">family =</span> binomial)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(glmmod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = cbind(total_resp, 4 - total_resp) ~ smoke, family = binomial, 
    data = binomial_df)

Coefficients:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -1.82124    0.07719 -23.595   &lt;2e-16 ***
smoke1       0.27156    0.12334   2.202   0.0277 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1045.3  on 536  degrees of freedom
Residual deviance: 1040.5  on 535  degrees of freedom
AIC: 1337.9

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>No, we cannot prove it. Since we are assuming within each group(<code>id</code>), the observations are independent, which is not true in this case. The assumption is violated hence the inference is not valid.</p>
<p><strong>(e) Answer:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>ohio<span class="sc">$</span>id <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(ohio<span class="sc">$</span>id)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>ohio<span class="sc">$</span>smoke <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(ohio<span class="sc">$</span>smoke)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>modpql <span class="ot">&lt;-</span> <span class="fu">glmmPQL</span>(resp <span class="sc">~</span> age <span class="sc">+</span> smoke,</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">random =</span> <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> id,</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">family =</span> binomial,</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data   =</span> ohio)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>iteration 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>iteration 2</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>iteration 3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>iteration 4</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>iteration 5</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>iteration 6</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>iteration 7</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>iteration 8</code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modpql)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed-effects model fit by maximum likelihood
  Data: ohio 
  AIC BIC logLik
   NA  NA     NA

Random effects:
 Formula: ~1 | id
        (Intercept)  Residual
StdDev:    2.057175 0.6355563

Variance function:
 Structure: fixed weights
 Formula: ~invwt 
Fixed effects:  resp ~ age + smoke 
                 Value  Std.Error   DF    t-value p-value
(Intercept) -2.7658365 0.14218299 1610 -19.452654  0.0000
age         -0.1815756 0.04365164 1610  -4.159652  0.0000
smoke1       0.3251839 0.23131699  535   1.405793  0.1604
 Correlation: 
       (Intr) age   
age     0.197       
smoke1 -0.591 -0.003

Standardized Within-Group Residuals:
       Min         Q1        Med         Q3        Max 
-2.6145143 -0.2829352 -0.2583719 -0.2154580  3.4443795 

Number of Observations: 2148
Number of Groups: 537 </code></pre>
</div>
</div>
<p><code>-</code>age`: For one year increases in age, the log odds of wheezing decreases by 0.1816 for a typical individual.</p>
<p><code>-</code>smoke`: The log odds of wheezing for a smoker is 0.3252 higher than for a non-smoker of the same age for typical individuals.</p>
<p>For one year increase in age, the odds of wheezing decrease by 16.61% for a typical individual.</p>
<p><strong>(f) Answer:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>modgh <span class="ot">&lt;-</span> <span class="fu">glmer</span>(resp <span class="sc">~</span> age <span class="sc">+</span> smoke <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">|</span> id), </span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">nAGQ     =</span> <span class="dv">25</span>,</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">family   =</span> poisson,</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">data     =</span> ohio)</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modgh)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Generalized linear mixed model fit by maximum likelihood (Adaptive
  Gauss-Hermite Quadrature, nAGQ = 25) [glmerMod]
 Family: poisson  ( log )
Formula: resp ~ age + smoke + (1 | id)
   Data: ohio

     AIC      BIC   logLik deviance df.resid 
  1145.4   1168.1   -568.7   1137.4     2144 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-0.7074 -0.2760 -0.2510 -0.2281  2.5872 

Random effects:
 Groups Name        Variance Std.Dev.
 id     (Intercept) 1.153    1.074   
Number of obs: 2148, groups:  id, 537

Fixed effects:
            Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -2.58178    0.13462 -19.179   &lt;2e-16 ***
age         -0.09596    0.04973  -1.929   0.0537 .  
smoke1       0.24806    0.16264   1.525   0.1272    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
       (Intr) age   
age     0.229       
smoke1 -0.479  0.000</code></pre>
</div>
</div>
<p>Compared with GLMM fit using penalized quasi-likelihood, this model gives a different estimates of the coefficient. The signs of the estimates are the same but the values are different. This model also indicates that age is not a significant predictor of wheezing while GLMM fit using penalized quasi-likelihood indicates that age is a significant predictor of wheezing.</p>
<p><strong>(g) Answer:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(INLA)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Loading required package: sp</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>This is INLA_24.05.01-1 built 2024-05-01 18:56:18 UTC.
 - See www.r-inla.org/contact-us for how to get help.
 - List available models/likelihoods/etc with inla.list.models()
 - Use inla.doc(&lt;NAME&gt;) to access documentation</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>inla_mod <span class="ot">&lt;-</span> <span class="fu">inla</span>(resp <span class="sc">~</span> age <span class="sc">+</span> smoke <span class="sc">+</span> <span class="fu">f</span>(id, <span class="at">model =</span> <span class="st">"iid"</span>), </span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">family =</span> <span class="st">"binomial"</span>, </span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> ohio, </span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">verbose =</span> <span class="cn">TRUE</span>)</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(inla_mod)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Time used:
    Pre = 0.697, Running = 0.413, Post = 0.0259, Total = 1.14 
Fixed effects:
              mean    sd 0.025quant 0.5quant 0.975quant   mode kld
(Intercept) -2.946 0.201     -3.360   -2.938     -2.574 -2.938   0
age         -0.173 0.063     -0.297   -0.173     -0.050 -0.173   0
smoke1       0.385 0.239     -0.083    0.384      0.858  0.384   0

Random effects:
  Name    Model
    id IID model

Model hyperparameters:
                  mean    sd 0.025quant 0.5quant 0.975quant  mode
Precision for id 0.276 0.047      0.196    0.272      0.378 0.265

Marginal log-Likelihood:  -834.98 
 is computed 
Posterior summaries for the linear predictor and the fitted values are computed
(Posterior marginals needs also 'control.compute=list(return.marginals.predictor=TRUE)')</code></pre>
</div>
</div>
<p>This model indicates that age is a significant predictor of wheezing while smoke is not a significant predictor of wheezing using 95% confidence interval.</p>
<p>The model says that one year increase in age, the log odds of wheezing decrease by 0.73 for a typical individual. It also says for a smoker, the log odds of wheezing is 0.385 higher than for a non-smoker of the same age for typical individuals.</p>
<p><strong>(i) Answer:</strong></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>modgeep <span class="ot">&lt;-</span> <span class="fu">geeglm</span>(resp <span class="sc">~</span> age <span class="sc">+</span> smoke,</span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">id        =</span> id, </span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">corstr    =</span> <span class="st">"ar1"</span>,</span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">scale.fix =</span> <span class="cn">TRUE</span>,</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">data      =</span> ohio,</span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">family    =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modgeep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
geeglm(formula = resp ~ age + smoke, family = binomial(link = "logit"), 
    data = ohio, id = id, corstr = "ar1", scale.fix = TRUE)

 Coefficients:
            Estimate  Std.err    Wald Pr(&gt;|W|)    
(Intercept) -1.90262  0.11533 272.174   &lt;2e-16 ***
age         -0.11490  0.04544   6.394   0.0115 *  
smoke1       0.23340  0.18137   1.656   0.1981    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation structure = ar1 
Scale is fixed.

  Link = identity 

Estimated Correlation Parameters:
      Estimate Std.err
alpha   0.5007 0.03799
Number of clusters:   537  Maximum cluster size: 4 </code></pre>
</div>
</div>
<p>The estimate of the alpha is 0.501. This reflects a moderate level of persistence in wheezing over time, indicating that children who wheeze at one time point have a moderate likelihood of wheezing at the next.</p>
<p><strong>(j) Answer:</strong></p>
<p>Smoker will have larger odds of wheezing than non-smoker of the same age. Increasing in age will have a negative effect on the odds of wheezing. The GLMM model is prefereable since it accounts for the correlation within the same individual.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>